name: Build BrowserFortify Executables

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            artifact_name: BrowserFortify-Windows.exe
          - os: ubuntu-latest  
            artifact_name: BrowserFortify-Linux
          - os: macos-latest
            artifact_name: BrowserFortify-macOS

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        # Install common dependencies
        pip install requests beautifulsoup4 lxml selenium webdriver-manager || true
      shell: bash
    
    - name: Build executable
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          pyinstaller --onefile --windowed --name BrowserFortify-Windows browserfortify.py
        else
          pyinstaller --onefile --name ${{ matrix.artifact_name }} browserfortify.py
        fi
      shell: bash
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifact_name }}
        path: dist/${{ matrix.artifact_name }}
    
    - name: Upload to release (if tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/${{ matrix.artifact_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
